/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesBookRouteImport } from './routes/resources.$book'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ResourcesBookChapterRouteImport } from './routes/resources.$book.$chapter'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBookRoute = ResourcesBookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => ResourcesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ResourcesBookChapterRoute = ResourcesBookChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => ResourcesBookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$book': typeof ResourcesBookRouteWithChildren
  '/resources/$book/$chapter': typeof ResourcesBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$book': typeof ResourcesBookRouteWithChildren
  '/resources/$book/$chapter': typeof ResourcesBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$book': typeof ResourcesBookRouteWithChildren
  '/resources/$book/$chapter': typeof ResourcesBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/publications'
    | '/research'
    | '/resources'
    | '/blog/$slug'
    | '/resources/$book'
    | '/resources/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/publications'
    | '/research'
    | '/resources'
    | '/blog/$slug'
    | '/resources/$book'
    | '/resources/$book/$chapter'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/publications'
    | '/research'
    | '/resources'
    | '/blog/$slug'
    | '/resources/$book'
    | '/resources/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$book': {
      id: '/resources/$book'
      path: '/$book'
      fullPath: '/resources/$book'
      preLoaderRoute: typeof ResourcesBookRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/resources/$book/$chapter': {
      id: '/resources/$book/$chapter'
      path: '/$chapter'
      fullPath: '/resources/$book/$chapter'
      preLoaderRoute: typeof ResourcesBookChapterRouteImport
      parentRoute: typeof ResourcesBookRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ResourcesBookRouteChildren {
  ResourcesBookChapterRoute: typeof ResourcesBookChapterRoute
}

const ResourcesBookRouteChildren: ResourcesBookRouteChildren = {
  ResourcesBookChapterRoute: ResourcesBookChapterRoute,
}

const ResourcesBookRouteWithChildren = ResourcesBookRoute._addFileChildren(
  ResourcesBookRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesBookRoute: typeof ResourcesBookRouteWithChildren
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesBookRoute: ResourcesBookRouteWithChildren,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
